<<<<<<< HEAD
# Generated by Django 5.0.1 on 2025-01-22 12:51
=======
# Generated by Django 5.0.1 on 2025-01-22 12:05
>>>>>>> f4ff9b8d1dafbd81acb0e16f3a508003b71c588b

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("botApp", "0030_usuario_edad"),
=======
        ('botApp', '0030_usuario_edad'),
>>>>>>> f4ff9b8d1dafbd81acb0e16f3a508003b71c588b
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="usuario",
            name="AnioNacimiento",
            field=models.DateField(verbose_name="Fecha de Nacimiento"),
=======
            model_name='usuario',
            name='AnioNacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
>>>>>>> f4ff9b8d1dafbd81acb0e16f3a508003b71c588b
        ),
    ]
