# Generated by Django 5.0.1 on 2025-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0032_ultima_mamografia_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultima_mamografia_anio',
            name='anio_ult_mamografia',
            field=models.IntegerField(default=0, verbose_name='Año de última mamografía'),
        ),
        migrations.AlterField(
            model_name='ultima_mamografia_anio',
            name='tiempo_transc_ult_mamografia',
            field=models.IntegerField(db_default=models.Value(0), verbose_name='Tiempo transcurrido'),
        ),
    ]
