# Generated by Django 5.0.1 on 2025-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0033_alter_ultima_mamografia_anio_anio_ult_mamografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultima_mamografia_anio',
            name='tiempo_transc_ult_mamografia',
            field=models.IntegerField(default=0, verbose_name='Tiempo transcurrido'),
        ),
    ]
