# Generated by Django 5.0.1 on 2025-01-30 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0034_alter_ultima_mamografia_anio_tiempo_transc_ult_mamografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID provincia')),
                ('cod_provincia', models.CharField(max_length=4)),
                ('nombre_provincia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID región')),
                ('cod_region', models.CharField(max_length=2)),
                ('nombre_region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='comuna_chile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID comuna')),
                ('cod_comuna', models.CharField(max_length=6)),
                ('nombre_comuna', models.CharField(max_length=200)),
                ('cod_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='provincia',
            name='cod_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.region'),
        ),
    ]
