# Generated by Django 5.0.1 on 2025-02-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0035_provincia_region_comuna_chile_provincia_cod_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregFactorRiesgoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factor de Riesgo Mod')),
                ('pregunta_FRM', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpcFactorRiesgoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opc Riesgo Mod')),
                ('opc_respuesta_FRM', models.CharField(max_length=200)),
                ('id_pregunta_FRM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregfactorriesgomod')),
            ],
        ),
        migrations.CreateModel(
            name='RespUsuarioFactorRiesgoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resp Riesgo Mod')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_FRM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opcfactorriesgomod')),
            ],
        ),
    ]
