# Generated by Django 5.0.1 on 2025-02-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0036_pregfactorriesgomod_opcfactorriesgomod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PregDeterSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Determinantes sociales salud')),
                ('pregunta_DS', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PregFactorRiesgoNoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Factor de Riesgo No Mod')),
                ('pregunta_FRNM', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OpcDeterSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opc determinantes salud')),
                ('opc_respuesta_DS', models.CharField(max_length=200)),
                ('id_pregunta_DS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregdetersalud')),
            ],
        ),
        migrations.CreateModel(
            name='OpcFactorRiesgoNoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Opc Riesgo No Mod')),
                ('opc_respuesta_FRNM', models.CharField(max_length=200)),
                ('id_pregunta_FRNM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.pregfactorriesgonomod')),
            ],
        ),
        migrations.CreateModel(
            name='RespDeterSalud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resp determinante salud')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_DS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opcdetersalud')),
            ],
        ),
        migrations.CreateModel(
            name='RespUsuarioFactorRiesgoNoMod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Resp Riesgo Mod')),
                ('Rut', models.CharField(max_length=10)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('respuesta_FRNM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botApp.opcfactorriesgonomod')),
            ],
        ),
    ]
