# Generated by Django 5.0.1 on 2025-02-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0038_respusuariofactorriesgonomod_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respusuariofactorriesgonomod',
            name='edad',
        ),
    ]
