# Generated by Django 5.0.1 on 2025-02-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0040_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
