# Generated by Django 5.0.1 on 2025-02-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0041_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='AnioNacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
