# Generated by Django 5.0.1 on 2025-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0042_alter_usuario_anionacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.CharField(max_length=30),
        ),
    ]
