# Generated by Django 5.0.1 on 2025-02-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0046_alter_usuario_anionacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_preg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID códigos preguntas')),
                ('codigo_preguntas', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RespTextoFRM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID índice antropométrico')),
                ('Rut', models.CharField(max_length=10)),
                ('peso_FRM6', models.IntegerField(default=0)),
                ('altura_FRM5', models.IntegerField(default=0)),
                ('imc', models.FloatField(default=0.0)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pregdetersalud',
            name='codigo_preguntas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg'),
        ),
        migrations.AddField(
            model_name='pregfactorriesgomod',
            name='codigo_preguntas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg'),
        ),
        migrations.AddField(
            model_name='pregfactorriesgonomod',
            name='codigo_preguntas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg'),
        ),
    ]
