# Generated by Django 5.0.1 on 2025-02-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0047_codigos_preg_resptextofrm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='codigo_preguntas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.codigos_preg'),
        ),
    ]
