# Generated by Django 5.0.1 on 2025-02-19 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0048_pregunta_codigo_preguntas'),
    ]

    operations = [
        #migrations.AddField(
            #model_name='resptextofrm',
            #name='id_usuario',
            #field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario'),
        #),
        migrations.AddField(
            model_name='ultima_mamografia_anio',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario'),
        ),
        migrations.AddField(
            model_name='usuariotextopregunta',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Rut',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
