# Generated by Django 5.0.1 on 2025-02-19 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0051_comuna_chile_id_usuario_alter_usuario_comuna_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ultima_mamografia_anio',
            name='fecha_pregunta',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
