# Generated by Django 5.0.1 on 2025-02-19 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0052_ultima_mamografia_anio_fecha_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='resptextofrm',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botApp.usuario'),
        ),
    ]
