# Generated by Django 5.0.1 on 2025-02-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0053_resptextofrm_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ultima_mamografia_anio',
            name='fecha_pregunta',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
