# Generated by Django 5.0.1 on 2025-02-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botApp', '0054_alter_ultima_mamografia_anio_fecha_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rut',
            field=models.CharField(max_length=10),
        ),
    ]
